In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

df = pd.read_csv('Downloads/CAR DETAILS FROM CAR DEKHO.csv')
df['Age'] = 2024-df['year']
x = df.drop(['selling_price','name','year'],axis=1)
y=df['selling_price']

x = pd.get_dummies(x)

poly = PolynomialFeatures(degree=3)

x_poly = poly.fit_transform(x)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=7)

lr = LinearRegression()

lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

print('r2Score:', r2_score(y_test, y_pred))
print('mean_squared_error:', mean_squared_error(y_test, y_pred))
print('mean_absolute_error:', mean_absolute_error(y_test, y_pred))

r2Score: 0.460888725189738
mean_squared_error: 151585982113.607
mean_absolute_error: 218187.39188375196


In [ ]:
# actual    predicated    
#  Y            Y          ---> TP
#  N            Y          ---> FP
#  Y            N          ---> FN
#  N            N          ---> TN

In [34]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn import metrics

df1 = pd.read_csv("Downloads/Iris.csv")

x = df1.drop('Species',axis=1)
y=df1['Species']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=4)

k_values = [3,5,7,9]
normal_accuracy = []

for i in range(0,len(k_values)) :
    knn = KNeighborsClassifier(n_neighbors=k_values[i])
    model = knn.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    accur = metrics.accuracy_score(y_test,y_pred)
    normal_accuracy.append(int(accur))
    
best_accur = max(normal_accuracy)

k_position = normal_accuracy[best_accur]

print(k_position)
knn = KNeighborsClassifier(n_neighbors=k_position)
model = knn.fit(x_train,y_train)
y_pred = model.predict(x_test)

cm = confusion_matrix(y_test,y_pred)
print(cm)


# cm = confusion_matrix(y_test,y_pred)
# print(cm)

1
[[16  0  0]
 [ 0  5  0]
 [ 0  0  9]]
